[project]
name = "cdk-tech-test"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-cdk-lib>=2.212.0",
    "constructs>=10.4.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
